from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langgraph.graph.message import add_messages

class ScenarioWorkflowState(TypedDict):
    """
    The central state dictionary (the "clipboard") that gets passed 
    between every node in the LangGraph workflow.
    """
    
    # --- 1. Conversation & Input ---
    # `add_messages` ensures new messages are appended, not overwritten
    messages: Annotated[list, add_messages] 
    
    # Multimodal query: {"text": "...", "images": ["path.jpg"], "videos": []}
    user_query: Dict[str, Any]
    
    # --- 2. Understanding & Retrieval ---
    # The structured parameters extracted from the user's query/feedback
    scenario_dsl: Dict[str, Any]
    
    # The numerical vector used to search Milvus
    query_embedding: List[float]
    
    # The ID of the closest match found in the vector database
    base_scenario_id: str
    
    # --- 3. The Working Canvas ---
    # The code actively being tested or adapted in the current loop
    current_scenic_code: str
    
    # --- 4. Simulation & Evaluation ---
    # Path to the video generated by the run_simulation node
    simulation_video_path: str
    
    # The score given by evaluate_with_vlm (e.g., 0.0 to 100.0)
    evaluation_score: float
    
    # The textual critique/differences identified by the VLM
    evaluation_feedback: str
    
    # --- 5. Best Result Tracking ---
    # Tracks the highest-scoring version in case a later adaptation breaks the code
    best_scenic_code: str
    best_score: float
    
    # --- 6. Human-in-the-Loop ---
    # Optional fields, populated only when the user reviews the scenario
    user_satisfied: Optional[bool]
    user_modification: Optional[Dict[str, Any]] # the same as user_query, can contain text, images, videos
    
    # --- 7. Loop Control ---
    # Current loop iteration (starts at 0)
    generation_count: int
    
    # Safety limit to break the loop (e.g., 3)
    max_count: int